"""Writes docs/original-ai.asm, the annotated disassembly of the original's AI, from ai.ctl."""
import os
import re
import subprocess
import sys

from skoolkit.traceutils import disassemble

from zx import ZX

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPSHOT = os.path.join(HERE, '.cache', 'game.z80')
OUT = os.path.join(HERE, '..', '..', 'docs', 'original-ai.asm')

HEADER = """\
; The computer player of Battle Ships (Hit-Pak / Elite, 1987, ZX Spectrum 48K)
; by Keith Burkhill, disassembled from the tape and annotated.
;
; Generated by scripts/original-ai/disasm.py from ai.ctl; the TypeScript port is
; packages/server/src/ai/original/machine.ts.
;
; Variables (IY = $FD00 throughout the game):
;   $FD03       joystick bits returned by AI_FRAME
;   $FD07-$FD0A random number shift register, big end first
;   $FD29       block with the fewest shots        $FD2B  blocks without a shot
;   $FD35       hunting picks left before the next peek; reset from $FDFE (29)
;   $FD58       player on turn (1 = computer)       $A4D8  address of the board shot at
;   $FD68       unhit cells of player 1's torpedo boat
;   $FDAD       player 1's ships afloat
;   $FDCB-$FDCC target (row, column); $FF = none
;   $FDCD       6 x 4 bytes per enemy ship, torpedo boat first: hits, -, counter, ship
;   $FDE8       about the average shots per block
;   $FDEA       shots left in this block or line   $FDEB  current block (0-15)
;   $FDEC-$FDED position in the block (row, column) $FDEE-$FDEF  hit being worked from
;   $FDF3       1 = hunting in lines                $FDF4  direction of the line
;   $A14A-$A14B cursor (row, column)                $FA65  this turn's shots, (col, row)..., $FF
;   $F900       shots per block, 2 bytes each
;
; Directions are 0-7 clockwise from up; cells are (D, E) = (column, row), row 0 at the top.
"""


def check_ctl(path):
    """Instruction comments must start and end on instruction boundaries and not overlap."""
    mem = ZX(SNAPSHOT).mem
    lines = open(path).read().splitlines()
    blocks = sorted((int(m.group(2), 16), m.group(1)) for m in
                    (re.match(r'^([bcsiW]) \$([0-9A-F]{4})', l) for l in lines) if m)
    starts = set()
    for (start, kind), (end, _) in zip(blocks, blocks[1:]):
        a = start
        while kind == 'c' and a < end:
            starts.add(a)
            a += disassemble(mem, a)[1]
        starts.add(a)
    ranges, kind, problems = [], None, []
    for l in lines:
        if m := re.match(r'^([bcsiW]) \$', l):
            kind = m.group(1)
        if (m := re.match(r'^  \$([0-9A-F]{4})(?:,(\d+))?', l)) and kind == 'c':
            a = int(m.group(1), 16)
            n = int(m.group(2) or 0) or disassemble(mem, a)[1]
            if a not in starts or a + n not in starts:
                problems.append(f'not on instruction boundaries: {l}')
            ranges.append((a, a + n, l))
    ranges.sort()
    problems += [f'overlap: {a[2]} / {b[2]}' for a, b in zip(ranges, ranges[1:]) if b[0] < a[1]]
    if problems:
        sys.exit('\n'.join(problems))


def main():
    check_ctl(os.path.join(HERE, 'ai.ctl'))
    tools = os.path.dirname(sys.executable)
    skool = subprocess.run(
        [os.path.join(tools, 'sna2skool.py'), '-H', '-c', os.path.join(HERE, 'ai.ctl'), '-w', '100', SNAPSHOT],
        check=True, capture_output=True, text=True).stdout
    skool_file = os.path.join(HERE, '.cache', 'ai.skool')
    open(skool_file, 'w').write(skool)
    asm = subprocess.run(
        [os.path.join(tools, 'skool2asm.py'), '-H', '-q', '-w', '-I', 'LineWidth=100', skool_file],
        check=True, capture_output=True, text=True)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write(HEADER + '\n' + asm.stdout)
    if asm.stderr:
        print(asm.stderr, file=sys.stderr)
    print('wrote', os.path.normpath(OUT))


if __name__ == '__main__':
    main()
