; The computer player of Battle Ships (Hit-Pak / Elite, 1987, ZX Spectrum 48K)
; by Keith Burkhill, disassembled from the tape and annotated.
;
; Generated by scripts/original-ai/disasm.py from ai.ctl; the TypeScript port is
; packages/server/src/ai/original/machine.ts.
;
; Variables (IY = $FD00 throughout the game):
;   $FD03       joystick bits returned by AI_FRAME
;   $FD07-$FD0A random number shift register, big end first
;   $FD29       block with the fewest shots        $FD2B  blocks without a shot
;   $FD35       hunting picks left before the next peek; reset from $FDFE (29)
;   $FD58       player on turn (1 = computer)       $A4D8  address of the board shot at
;   $FD68       unhit cells of player 1's torpedo boat
;   $FDAD       player 1's ships afloat
;   $FDCB-$FDCC target (row, column); $FF = none
;   $FDCD       6 x 4 bytes per enemy ship, torpedo boat first: hits, -, counter, ship
;   $FDE8       about the average shots per block
;   $FDEA       shots left in this block or line   $FDEB  current block (0-15)
;   $FDEC-$FDED position in the block (row, column) $FDEE-$FDEF  hit being worked from
;   $FDF3       1 = hunting in lines                $FDF4  direction of the line
;   $A14A-$A14B cursor (row, column)                $FA65  this turn's shots, (col, row)..., $FF
;   $F900       shots per block, 2 bytes each
;
; Directions are 0-7 clockwise from up; cells are (D, E) = (column, row), row 0 at the top.

  ORG $97F8

; Random number, keeping HL
;
; Like RANDOM, but preserves HL.
;
; O:A Random byte
RND_KEEP_HL:
  PUSH HL                 ; Save HL around the call.
  CALL RANDOM             ;
  POP HL                  ;
  RET                     ;

; Random number
;
; A 32-bit shift register at $FD07-$FD0A, big end first. Each call shifts it
; left by one bit, feeding in bit 30 XOR bit 27 (bits 6 and 3 of $FD07), and
; returns the top byte. The polynomial is primitive, so the sequence only
; repeats after 2^31-1 calls; but two calls in a row return bytes that share 7
; bits, which matters at NA_START.
;
; O:A Random byte (the new value of $FD07)
; O:HL $FD07
;
; Work out bit 30 XOR bit 27, and put it in the carry flag.
RANDOM:
  LD A,($FD07)            ; A = top byte
  AND $48                 ; Keep bits 6 and 3
  ADD A,$38               ; 00 -> 38, 08 -> 40, 40 -> 78, 48 -> 80: bit 6 of
                          ; the sum is set just when one of them was
  RLA                     ; Two rotations bring bit 6 into the carry
  RLA                     ;
; Shift the register left, the carry going in at the bottom.
  LD HL,$FD0A             ; Bottom byte first
  RL (HL)
  DEC L
  RL (HL)
  DEC L
  RL (HL)
  DEC L
  RL (HL)                 ; Top byte
  LD A,(HL)               ; Return it
  RET                     ;



; Address of a cell
;
; The board being shot at is 20x20 bytes, row by row, row 0 at the top of the
; screen: 0 open sea, 1-6 a ship (by ship number: 1 carrier, 2 cruiser, 3
; submarine, 4 and 5 destroyers, 6 torpedo boat), $80 + ship number once hit,
; $FF a miss.
;
; I:D Column (0-19)
; I:E Row (0-19)
; O:HL Address of the cell
CELL_ADDR:
  BIT 6,(IY+$23)          ; While bit 6 of $FD23 is set every cell reads as
                          ; $FD2D (not in play)
  JR NZ,$99DE
  PUSH DE                 ; Save DE
  LD A,E                  ; L = 10 * row
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,E                 ;
  ADD A,A                 ;
  LD L,A                  ;
  LD H,$00                ; HL = 10 * row
  LD E,D                  ; DE = column
  LD D,H                  ;
  ADD HL,HL               ; HL = 20 * row + column
  ADD HL,DE               ;
  LD DE,($A4D8)           ; Add the address of the board ($A4D8: $6100 for
  ADD HL,DE               ; player 1, $6300 for player 2)
  POP DE                  ;
  RET

; Is this a good cell to hunt?
;
; A ship could lie across it (ROOM_FOR_SHIP), and it hasn't been shot yet.
;
; I:DE Cell
; O:F Z set if it's good
HUNTABLE:
  CALL ROOM_FOR_SHIP      ; Not if no ship fits here or it's already planned
  RET NZ                  ;
  CALL CELL               ; Z if bit 7 (shot) is clear
  BIT 7,A                 ;
  RET

; Read a cell
;
; Used by the routines at HUNTABLE, UNUSED_1, ROOM_FOR_SHIP, FITS,
; NEXT_TO_HITS, ODD_SHIP, STRAIGHT_SHIP, LINE_SHOT, HUNT and NEW_AREA.
;
; I:DE Cell
; O:A What's there
; O:F Z if open sea
CELL:
  PUSH HL                 ; Preserve HL
  CALL CELL_ADDR          ;
  LD A,(HL)               ;
  POP HL                  ;
  OR A                    ;
  RET                     ;

; Unused: is a cell shot or planned?
;
; Only called by the unused UNUSED_2. Carry set if the cell has been shot or is
; in the plan.
UNUSED_1:
  CALL CELL
  RLA
  RET C
; Look for it in the plan.
  LD HL,$FA65
UNUSED_1_0:
  LD A,(HL)
  INC A
  JR Z,UNUSED_1_3
  DEC A
  INC HL
  CP D
  JR NZ,UNUSED_1_1
  LD A,(HL)
  CP E
  JR Z,UNUSED_1_2
UNUSED_1_1:
  INC HL
  JR UNUSED_1_0
UNUSED_1_2:
  SCF
  RET
UNUSED_1_3:
  XOR A
  RET

; Ship sizes
;
; Indexed from $9A29 by ship number (SHIP_DAMAGE).
SHIP_SIZES:
  DEFB $06,$05,$04,$03,$03,$02 ; Carrier 6, cruiser 5, submarine 4, destroyers
                               ; 3 and 3, torpedo boat 2

; Damage per enemy ship
;
; Counts the hits on each enemy ship, straight from the ship numbers on the
; board: so the AI knows which hit belongs to which ship, even when a salvo hit
; two ships at once. Fills the first byte of six 4-byte entries at $FDCD,
; torpedo boat first: the hits, or 0 for a ship that is untouched or sunk.
;
; The rest of each entry: +2 is a loop counter for ALONG_LINE, +3 the ship
; being worked on (ODD_SHIP), cleared at the start of every turn.
SHIP_DAMAGE:
  LD IX,$FDCD             ; IX = entry for ship 6; B = ship number
  LD B,$06                ;
SD_SHIP:
  LD HL,($A4D8)           ; From the top of the board
  LD DE,$0190             ; 400 cells
  LD C,$00                ; C = hits
  SET 7,B                 ; B = what a hit on this ship looks like
SD_COUNT:
  LD A,(HL)               ; Count it
  CP B                    ;
  JR NZ,SHIP_DAMAGE_0     ;
  INC C                   ;
SHIP_DAMAGE_0:
  INC HL                  ; Next cell
  DEC DE                  ;
  LD A,D                  ;
  OR E                    ;
  JR NZ,SD_COUNT          ;
  LD DE,$9A29             ; DE = size of the ship, from the table at $9A2A
  LD A,B                  ;
  AND $7F                 ;
  ADD A,E                 ;
  LD E,A                  ;
  JR NC,SHIP_DAMAGE_1     ;
  INC D                   ;
SHIP_DAMAGE_1:
  LD A,(DE)               ; A = 0 if hits = size (sunk), else the hits
  SUB C                   ;
  JR Z,SHIP_DAMAGE_2      ;
  LD A,C                  ;
SHIP_DAMAGE_2:
  LD (IX+$00),A           ; Store in the entry
  RES 7,B                 ; Next entry, next ship
  LD DE,$0004             ;
  ADD IX,DE               ;
  DJNZ SD_SHIP
  RET

; Shots per block
;
; The sea is 16 blocks of 5x5 cells, numbered row by row from the top left. For
; each one this counts the shots, both fired and planned for this turn, into
; $F900 + 2 * block (and the hits into the byte after, which nothing reads). It
; also finds the block with the fewest shots ($FD29, the later one if several),
; counts the blocks without a single shot ($FD2B), and works out about the
; average shots per block ($FDE8).
;
; First the shots planned this turn, a list of (column, row) pairs at $FA65
; ending with $FF.
BLOCK_STATS:
  LD IX,$F900             ; 16 blocks
  LD B,$10                ;
BS_PLANNED:
  LD (IX+$00),$00         ; Clear its counts
  LD (IX+$01),$00         ;
  PUSH BC                 ; A = block number
  LD A,$10                ;
  SUB B                   ;
  PUSH AF                 ; E = first row of the block (5 * (block / 4))
  AND $0C                 ;
  RRA                     ;
  RRA                     ;
  LD E,A                  ;
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,E                 ;
  LD E,A                  ;
  POP AF                  ;
  AND $03                 ; D = first column (5 * (block mod 4))
  LD D,A                  ;
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,D                 ;
  LD D,A                  ;
  LD HL,$FA65             ; The plan
BS_PLAN_LOOP:
  LD A,(HL)               ; End of the list?
  INC HL                  ;
  INC A                   ;
  JR Z,BS_PLAN_DONE       ;
  DEC A                   ; Is the column in the block?
  SUB D                   ;
  JR C,BS_PLAN_NEXT       ;
  SUB $05                 ;
  JR NC,BS_PLAN_NEXT
  LD A,(HL)               ; And the row?
  SUB E                   ;
  JR C,BS_PLAN_NEXT       ;
  SUB $05                 ;
  JR NC,BS_PLAN_NEXT      ;
  INC (IX+$00)            ; Then count it
BS_PLAN_NEXT:
  INC HL
  JR BS_PLAN_LOOP
BS_PLAN_DONE:
  INC IX                  ; Next block
  INC IX                  ;
  POP BC                  ;
  DJNZ BS_PLANNED         ;
; Then the shots fired, and the rest.
  LD IX,$F900             ; Back to the first block
  XOR A                   ; Total shots, total hits and untouched blocks = 0
  LD ($FDF0),A            ;
  LD ($FDF1),A            ;
  LD ($FDF2),A            ;
  LD ($FD2B),A            ;
  LD (IY+$2A),$FF         ; Fewest shots so far = 255
  LD B,$10                ; 16 blocks
BS_FIRED:
  PUSH BC
  LD DE,($A4D8)           ; DE = the board
  LD A,$10                ; A = block number
  SUB B                   ;
  PUSH AF                 ;
  AND $0C                 ; HL = 100 * (block / 4) (5 rows of 20 cells per
  RRA                     ; block row)...
  RRA                     ;
  LD L,A                  ;
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,L                 ;
  LD C,A                  ;
  ADD A,A                 ;
  LD L,A                  ;
  LD H,$00                ;
  LD B,$00                ;
  ADD HL,HL               ;
  ADD HL,BC               ;
  ADD HL,HL               ;
  ADD HL,HL               ;
  POP AF                  ; ... + 5 * (block mod 4)
  AND $03                 ;
  LD C,A                  ;
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,C                 ;
  LD C,A                  ;
  ADD HL,BC               ;
  ADD HL,DE               ;
  LD C,$05                ; 5 rows
BS_ROW:
  LD B,$05                ; 5 columns
BS_CELL:
  LD A,(HL)               ; Not shot?
  BIT 7,A                 ;
  JR Z,BS_NEXT_CELL       ;
  INC (IX+$00)            ; Count a shot
  INC A                   ; A hit, if it isn't a miss
  JR Z,BS_NEXT_CELL       ;
  INC (IX+$01)            ;
BS_NEXT_CELL:
  INC HL
  DJNZ BS_CELL
  LD DE,$000F             ; Next row of the block
  ADD HL,DE               ;
  DEC C
  JR NZ,BS_ROW
  LD HL,($FDF0)           ; Add the block's shots to the total
  LD E,(IX+$00)           ;
  ADD HL,DE               ;
  LD ($FDF0),HL           ;
  INC E                   ; Count the block if it has none
  DEC E                   ;
  JR NZ,BS_FEWEST         ;
  INC (IY+$2B)            ;
BS_FEWEST:
  LD A,($FD2A)            ; The fewest so far (<=: the later block wins a tie)?
  CP E                    ; Remember it and its number
  JR C,BS_AVERAGE         ;
  LD (IY+$2A),E           ;
  POP BC                  ;
  PUSH BC                 ;
  LD A,$10                ;
  SUB B                   ;
  LD (IY+$29),A           ;
BS_AVERAGE:
  RR H                    ; $FDE8 = (total / 2) AND $F0, divided by 8: about
  RR L                    ; total / 16, rounded down to even
  LD A,L                  ;
  AND $F0                 ;
  RRA                     ;
  RRA                     ;
  RRA                     ;
  LD ($FDE8),A            ;
  LD A,($FDF2)            ; $FDE9 = (total hits AND $F0) / 16 (never used)
  ADD A,(IX+$01)          ;
  LD ($FDF2),A            ;
  AND $F0                 ;
  RRA                     ;
  RRA                     ;
  RRA                     ;
  RRA                     ;
  LD ($FDE9),A            ;
  INC IX                  ; Next block
  INC IX                  ;
  POP BC                  ;
  DEC B                   ;
  JP NZ,BS_FIRED          ;
  RET

; Could a ship lie across this cell?
;
; No if the cell is already planned. Otherwise yes if, in some direction, the
; neighbour isn't a miss and either the enemy's torpedo boat (the only 2-cell
; ship) is still afloat or the cell beyond isn't a miss either.
;
; The idea was also to accept a cell with good neighbours on both sides, but
; the code loads the address where it saved the cell rather than the cell
; itself ($11 at $9B88 should have been $ED,$5B), and every step from column
; $9B is off the board.
;
; I:DE Cell
; O:F Z if a ship fits
ROOM_FOR_SHIP:
  CALL PLANNED            ; Not if it's planned already
  RET NZ                  ;
  PUSH BC                 ; Save registers
  PUSH HL                 ;
  PUSH DE                 ;
  PUSH AF                 ;
  LD ($9B64),DE           ; Keep the cell in the operand at $9B64
  LD B,$08                ; 8 directions
RS_DIRECTION:
  LD DE,$0000             ; DE = the cell (self-modified)
  LD A,B                  ; HL = direction B mod 8
  AND $07                 ;
  CALL DIRECTION          ;
  CALL STEP               ; Step; off the board?
  JR NC,RS_NEXT
  CALL CELL               ; A miss?
  INC A                   ;
  JR Z,RS_NEXT
  LD A,($FD68)            ; Enemy torpedo boat still afloat ($FD68 is its unhit
  OR A                    ; cells)? Then this will do
  JR NZ,RS_YES
  CALL STEP               ; One more step
  JR NC,RS_BUG
  CALL CELL               ; Not a miss either? Then this will do
  INC A                   ;
  JR NZ,RS_YES
RS_BUG:
  LD DE,$9B64             ; Meant to reload the cell, but this loads its
                          ; address: D = $9B, E = $64
  LD A,B                  ; The opposite direction
  AND $07                 ;
  XOR $04                 ;
  CALL DIRECTION          ; Step from column $9B: always off the board
  CALL STEP               ;
  JR NC,RS_NEXT
  CALL CELL               ; (never gets here)
  INC A                   ;
  JR Z,RS_NEXT
RS_YES:
  POP DE                  ; Z: yes
  XOR A                   ;
RS_RETURN:
  LD A,D                  ; Restore registers and return
  POP DE                  ;
  POP HL                  ;
  POP BC                  ;
  RET                     ;
RS_NEXT:
  DJNZ RS_DIRECTION       ; Next direction
  POP DE                  ; NZ: no
  LD A,$01                ;
  INC A                   ;
  JR RS_RETURN            ;

; Is this cell planned already?
;
; Looks for it in this turn's list of shots at $FA65.
;
; I:DE Cell
; O:F NZ if it's in the list
PLANNED:
  PUSH HL                 ; From the start of the list
  PUSH AF                 ;
  LD HL,$FA65             ;
PL_LOOP:
  LD A,(HL)               ; End of the list? (Z)
  INC HL                  ;
  INC A                   ;
  JR Z,PL_RETURN          ;
  DEC A                   ; Column matches?
  CP D                    ;
  JR NZ,PL_NEXT           ;
  LD A,(HL)               ; And the row? (Z)
  SUB E                   ;
  JR Z,PL_FOUND           ;
PL_NEXT:
  INC HL
  JR PL_LOOP
PL_FOUND:
  INC A                   ; A = 1: NZ
PL_RETURN:
  POP HL                  ; Restore A and HL, keeping the flags
  LD A,H                  ;
  POP HL                  ;
  RET                     ;

; Find a cell holding a value
;
; Searches from HL for the first byte equal to B (at $9BC7) or to B + $80, a
; hit on ship B (at FIND_HIT), and works out its row and column. There is no
; end to the search: past the board it goes on through memory. Every start the
; game gives it finds something with a row of 20 or more, which the callers
; take as not found.
;
; I:B Value, or ship number at FIND_HIT
; I:HL Where to start
; O:DE Cell (column, row)
; O:HL Its address
; O:F Carry if it's on the board
FIND_VALUE:
  PUSH BC
  PUSH AF
  JR FV_LOOP
; This entry point is used by the routines at SECOND_HIT, ODD_SHIP and
; STRAIGHT_SHIP.
FIND_HIT:
  PUSH BC                 ; A hit on ship B
  PUSH AF                 ;
  SET 7,B                 ;
FV_LOOP:
  LD A,(HL)               ; Find it
  CP B                    ;
  JR Z,FV_FOUND           ;
  INC HL                  ;
  JR FV_LOOP              ;
FV_FOUND:
  PUSH HL                 ; HL = offset from the start of the board
  LD DE,($A4D8)           ;
  XOR A                   ;
  SBC HL,DE               ;
  LD DE,$0014             ; B = row: count how many times 20 goes into it
  LD B,$00                ;
FV_ROW:
  SBC HL,DE
  JR C,FV_COLUMN
  INC B
  JR FV_ROW
FV_COLUMN:
  ADD HL,DE               ; D = column, E = row
  LD E,B                  ;
  LD D,L                  ;
  LD A,D                  ; Carry if both are under 20
  CP $14                  ;
  JR NC,FV_RETURN         ;
  LD A,E                  ;
  CP $14                  ;
FV_RETURN:
  POP HL                  ; Restore HL (the address found), A and BC
  POP BC                  ;
  LD A,B                  ;
  POP BC                  ;
  RET                     ;



; Ship shapes
;
; Pointers to the shapes of each ship (by ship number - 1; the destroyers share
; one), then the shapes: 8 orientations of 10 bytes, up to 5 (dx, dy) pairs
; from the ship's origin cell, ending early with (0, 0).
SHAPE_PTRS:
  DEFW $A21D
  DEFW $A26D
  DEFW $A2BD
  DEFW $A35D
  DEFW $A35D
  DEFW $A3AD
  DEFB $FF,$00,$01,$00,$FF,$FF,$FE,$FF,$00,$FF ; Carrier: each orientation
  DEFB $FF,$00,$01,$00,$FF,$FF,$FE,$FF,$00,$FF ; twice; the 4 entries are 2
  DEFB $00,$FF,$00,$01,$01,$00,$01,$FF,$01,$FE ; shapes with different origins
  DEFB $00,$FF,$00,$01,$01,$00,$01,$FF,$01,$FE ;
  DEFB $FF,$00,$01,$00,$00,$01,$01,$01,$02,$01 ;
  DEFB $FF,$00,$01,$00,$00,$01,$01,$01,$02,$01 ;
  DEFB $FF,$00,$FF,$01,$FF,$02,$00,$01,$00,$FF ;
  DEFB $FF,$00,$FF,$01,$FF,$02,$00,$01,$00,$FF ;
  DEFB $FF,$00,$01,$00,$FE,$00,$02,$00,$00,$00 ; Cruiser: horizontal, diagonal,
  DEFB $FF,$FF,$01,$01,$FE,$FE,$02,$02,$00,$00 ; vertical, the other diagonal,
  DEFB $00,$FF,$00,$01,$00,$FE,$00,$02,$00,$00 ; then again
  DEFB $FF,$01,$01,$FF,$FE,$02,$02,$FE,$00,$00 ;
  DEFB $FF,$00,$01,$00,$FE,$00,$02,$00,$00,$00 ;
  DEFB $FF,$FF,$01,$01,$FE,$FE,$02,$02,$00,$00 ;
  DEFB $00,$FF,$00,$01,$00,$FE,$00,$02,$00,$00 ;
  DEFB $FF,$01,$01,$FF,$FE,$02,$02,$FE,$00,$00 ;
  DEFB $FF,$00,$01,$00,$00,$FF,$00,$00,$00,$00 ; Submarine: each orientation
  DEFB $FF,$00,$01,$00,$00,$FF,$00,$00,$00,$00 ; twice
  DEFB $00,$01,$01,$00,$00,$FF,$00,$00,$00,$00 ;
  DEFB $00,$01,$01,$00,$00,$FF,$00,$00,$00,$00 ;
  DEFB $FF,$00,$01,$00,$00,$01,$00,$00,$00,$00 ;
  DEFB $FF,$00,$01,$00,$00,$01,$00,$00,$00,$00 ;
  DEFB $FF,$00,$00,$FF,$00,$01,$00,$00,$00,$00 ;
  DEFB $FF,$00,$00,$FF,$00,$01,$00,$00,$00,$00 ;
  DEFB $FF,$00,$01,$00,$00,$FF,$00,$00,$00,$00 ; An unused copy of the
  DEFB $FF,$00,$01,$00,$00,$FF,$00,$00,$00,$00 ; submarine's
  DEFB $00,$01,$01,$00,$00,$FF,$00,$00,$00,$00 ;
  DEFB $00,$01,$01,$00,$00,$FF,$00,$00,$00,$00 ;
  DEFB $FF,$00,$01,$00,$00,$01,$00,$00,$00,$00 ;
  DEFB $FF,$00,$01,$00,$00,$01,$00,$00,$00,$00 ;
  DEFB $FF,$00,$00,$FF,$00,$01,$00,$00,$00,$00 ;
  DEFB $FF,$00,$00,$FF,$00,$01,$00,$00,$00,$00 ;
  DEFB $FF,$00,$01,$00,$00,$00,$00,$00,$00,$00 ; Destroyers
  DEFB $FF,$FF,$01,$01,$00,$00,$00,$00,$00,$00 ;
  DEFB $00,$FF,$00,$01,$00,$00,$00,$00,$00,$00 ;
  DEFB $FF,$01,$01,$FF,$00,$00,$00,$00,$00,$00 ;
  DEFB $FF,$00,$01,$00,$00,$00,$00,$00,$00,$00 ;
  DEFB $FF,$FF,$01,$01,$00,$00,$00,$00,$00,$00 ;
  DEFB $00,$FF,$00,$01,$00,$00,$00,$00,$00,$00 ;
  DEFB $01,$FF,$FF,$01,$00,$00,$00,$00,$00,$00 ;
  DEFB $FF,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; Torpedo boat: the second cell
  DEFB $FF,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ; in each of the 8 directions
  DEFB $00,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ;
  DEFB $01,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ;
  DEFB $01,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;
  DEFB $01,$01,$00,$00,$00,$00,$00,$00,$00,$00 ;
  DEFB $00,$01,$00,$00,$00,$00,$00,$00,$00,$00 ;
  DEFB $FF,$01,$00,$00,$00,$00,$00,$00,$00,$00 ;

; Place a fleet at random
;
; Places ships 6 down to 1: each at a random origin 2-17 cells from the top and
; left, in a random orientation, again and again until it fits (FITS). Checks
; the board of player A, but draws on player 2's (DRAW_SHIP); the game only
; calls it for the computer's fleet.
;
; I:A Player (1 for player 1's board, otherwise player 2's)
PLACE_FLEET:
  LD HL,$6100             ; Point $A4D8 at the board
  DEC A                   ;
  JR NZ,PLACE_FLEET_0     ;
  LD HL,$6300             ;
PLACE_FLEET_0:
  LD ($A4D8),HL           ;
  LD B,$06                ; Ship 6 first
PF_TRY:
  CALL RANDOM             ; E = row: 2-17
  AND $0F                 ;
  INC A                   ;
  INC A                   ;
  CP $14                  ;
  JR NC,PF_TRY            ;
  LD E,A
PF_COLUMN:
  CALL RANDOM             ; D = column: 2-17
  AND $0F                 ;
  INC A                   ;
  INC A                   ;
  CP $14                  ;
  JR NC,PF_COLUMN         ;
  LD D,A
  CALL RANDOM             ; C = orientation: 0-7
  AND $07                 ;
  LD C,A                  ;
  CALL FITS               ; Try again if it doesn't fit
  JR NZ,PF_TRY            ;
  LD HL,$FD7D             ; Note origin and orientation at $FD7D + 3 * (ship -
  LD A,B                  ; 1)
  ADD A,A                 ;
  ADD A,B                 ;
  SUB $03                 ;
  ADD A,L                 ;
  LD L,A                  ;
  LD (HL),D               ;
  INC L                   ;
  LD (HL),E               ;
  INC L                   ;
  LD (HL),C               ;
  PUSH BC                 ; Draw it
  LD A,B                  ;
  CALL DRAW_SHIP          ;
  POP BC                  ; Next ship
  DJNZ PF_TRY             ;
  RET

; Does a ship fit here?
;
; Every cell of the ship must be on the board, and every cell in or around it
; (the 3x3 square around each cell) that is on the board must be open sea:
; ships never touch, not even at the corners.
;
; I:B Ship number
; I:C Orientation
; I:DE Origin (column, row)
; O:F Z if it fits
FITS:
  PUSH BC                 ; Origin off the board? (It never is)
  PUSH DE                 ;
  LD A,$13                ;
  CP D                    ;
  JP C,FT_NO              ;
  CP E                    ;
  JP C,FT_NO
  DEC B                   ; IX = the shape
  CALL SHAPE              ;
  INC B                   ;
  LD H,D                  ; HL = origin
  LD L,E                  ;
  LD B,$06                ; Up to 6 cells; the origin first
  JR FT_AROUND            ;
FT_CELL:
  LD A,(IX+$00)           ; (0, 0) ends the shape
  OR (IX+$01)             ;
  JR Z,FT_FITS            ;
  LD A,(IX+$00)           ; Column of the next cell; on the board?
  ADD A,H                 ;
  LD D,A                  ;
  CP $14                  ;
  JR NC,FT_NO             ;
  INC IX                  ; Row; on the board?
  LD A,(IX+$00)           ;
  INC IX                  ;
  ADD A,L                 ;
  LD E,A                  ;
  CP $14                  ;
  JR NC,FT_NO
FT_AROUND:
  CALL FT_CHECK           ; Check the cell and its 8 neighbours
  INC D                   ;
  CALL FT_CHECK           ;
  DEC D                   ;
  DEC D                   ;
  CALL FT_CHECK           ;
  INC D                   ;
  INC E                   ;
  CALL FT_CHECK           ;
  DEC D                   ;
  CALL FT_CHECK           ;
  INC D                   ;
  INC D                   ;
  CALL FT_CHECK           ;
  DEC D                   ;
  DEC E                   ;
  DEC E                   ;
  CALL FT_CHECK           ;
  DEC D                   ;
  CALL FT_CHECK           ;
  INC D                   ;
  INC D                   ;
  CALL FT_CHECK           ;
  DEC D                   ;
  INC E                   ;
  DJNZ FT_CELL            ; Next cell
FT_FITS:
  POP DE                  ; Z: it fits
  POP BC                  ;
  XOR A                   ;
  RET                     ;
FT_CHECK:
  LD A,$13                ; Off the board? Doesn't matter
  CP D                    ;
  RET C                   ;
  CP E                    ;
  RET C                   ;
  CALL CELL               ; Open sea? Fine
  RET Z                   ;
  POP DE                  ; Otherwise drop the return address...
FT_NO:
  POP DE                  ; ... and return NZ: it doesn't fit
  POP BC                  ;
  LD A,$01                ;
  INC A                   ;
  RET                     ;

; Draw a ship on player 2's board
;
; Used by the routine at PLACE_FLEET.
;
; I:A Ship number
; I:B Ship number
DRAW_SHIP:
  EX AF,AF'               ; E = column, D = row, C = orientation, from the note
  DEC B                   ; made by PLACE_FLEET
  LD A,B                  ;
  ADD A,A                 ;
  ADD A,B                 ;
  LD HL,$FD7D             ;
  ADD A,L                 ;
  LD L,A                  ;
  LD E,(HL)               ;
  INC L                   ;
  LD D,(HL)               ;
  INC L                   ;
  LD C,(HL)               ;
  LD A,D                  ; HL = 20 * row + column
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,D                 ;
  ADD A,A                 ;
  LD L,A                  ;
  LD H,$00                ;
  LD D,H                  ;
  ADD HL,HL               ;
  ADD HL,DE               ;
  LD DE,$6300             ; On player 2's board
  ADD HL,DE               ;
  EX DE,HL                ; IX = the shape
  CALL SHAPE              ;
  EX DE,HL                ; Mark the origin
  LD B,$05                ;
  EX AF,AF'               ;
  LD (HL),A               ;
  EX AF,AF'               ;
DS_CELL:
  LD A,(IX+$00)           ; (0, 0) ends the shape
  OR (IX+$01)             ;
  JR Z,DS_DONE            ;
  PUSH HL                 ; Add dx
  LD E,(IX+$00)           ;
  LD D,$00                ;
  BIT 7,E                 ;
  JR Z,DRAW_SHIP_0        ;
  DEC D                   ;
DRAW_SHIP_0:
  ADD HL,DE               ;
  INC IX                  ; Add 20 * dy (dy is -2..2)
  LD A,(IX+$00)           ;
  LD DE,$0000             ;
  INC IX                  ;
  OR A                    ;
  JR Z,DRAW_SHIP_1        ;
  LD DE,$FFD8             ;
  ADD A,$02               ;
  JR Z,DRAW_SHIP_1        ;
  DEC A                   ;
  LD E,$EC                ;
  JR Z,DRAW_SHIP_1        ;
  DEC A                   ;
  DEC A                   ;
  LD DE,$0014             ;
  JR Z,DRAW_SHIP_1        ;
  LD E,$28                ;
DRAW_SHIP_1:
  ADD HL,DE
  EX AF,AF'               ; Mark the cell
  LD (HL),A               ;
  EX AF,AF'               ;
  POP HL                  ;
  DJNZ DS_CELL            ; Next
DS_DONE:
  RET

; Find a shape
;
; Used by the routines at FITS and DRAW_SHIP.
;
; I:B Ship number - 1
; I:C Orientation
; O:IX The shape
SHAPE:
  LD A,B                  ; HL = pointer for the ship
  LD HL,SHAPE_PTRS        ;
  ADD A,A                 ;
  ADD A,L                 ;
  LD L,A                  ;
  JR NC,SHAPE_0           ;
  INC H                   ;
SHAPE_0:
  LD A,(HL)
  INC HL
  LD H,(HL)
  LD L,A
  LD A,C                  ; + 10 * orientation
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,C                 ;
  ADD A,A                 ;
  ADD A,L                 ;
  LD L,A                  ;
  JR NC,SHAPE_1           ;
  INC H                   ;
SHAPE_1:
  PUSH HL                 ;
  POP IX                  ;
  RET



; The computer's joystick
;
; Runs every 5 frames while a player aims (from the loop at $B2AA), and returns
; in $FD03 the joystick bits that the loop then acts on, like a player's: bits
; 0-3 move the cursor left, right, up, down; bit 4 fires, which adds the cell
; under the cursor to the plan ($FA65), or takes it off if it's there already,
; and does nothing on a cell shot before. The salvo goes once the plan is full.
;
; When the computer has no target ($FDCB = $FF), this picks one, and the cursor
; doesn't move that time. Then it steers the cursor to the target (diagonally
; where it can), and fires when it's there.
;
; O:A Joystick bits (also in $FD03)
AI_FRAME:
  BIT 3,(IY+$06)          ; A human player in multi-play mode? Read the keys
  JP NZ,$9672             ;
  LD A,($FD58)            ; Player 1's turn? Read the keys
  DEC A                   ;
  JP NZ,$9672             ;
  LD HL,($FDCB)           ; The target: L = row, H = column
  LD DE,($A14A)           ; The cursor: E = row, D = column
  INC L                   ; No target? Pick one
  JR Z,PICK               ;
  DEC L                   ;
  LD C,$00                ; C = joystick bits
  LD A,H                  ; Same column?
  CP D                    ;
  JR Z,AF_ROWS            ;
  JR C,AF_LEFT            ; Target to the right: bit 1
  SET 1,C                 ;
  JR AF_ROWS              ;
AF_LEFT:
  SET 0,C                 ; To the left: bit 0
AF_ROWS:
  LD A,L                  ; Same row?
  SUB E                   ;
  JR Z,AF_THERE           ;
  JR C,AF_UP              ; Target below: bit 3
  SET 3,C                 ;
  JR AF_THERE
AF_UP:
  SET 2,C                 ; Above: bit 2
AF_THERE:
  INC C                   ; Moving?
  DEC C                   ;
  JR NZ,AF_SEND           ;
  SET 4,C                 ; No: we're there. Fire, and forget the target
  LD A,$FF                ;
  LD ($FDCB),A            ;
AF_SEND:
  LD A,C
  LD ($FD03),A
  RET
; Pick a target. First, what do we know about the enemy fleet?
PICK:
  CALL SHIP_DAMAGE        ; Hits per ship, shots per block
  CALL BLOCK_STATS        ;
; Work on the first ship, torpedo boat to carrier, that is damaged but afloat;
; if nothing works for it (NEXT_SHIP), the next one.
  LD IX,$FDCD
  LD A,$06
PK_SHIP:
  LD ($A73E),A            ; Ship number, kept in the operand at $A73E; B = ship
  LD B,A                  ; number
  LD A,(IX+$00)           ; Damaged and afloat?
  OR A                    ;
  JR NZ,PK_DAMAGED        ;
; This entry point is used by the routines at ODD_SHIP and STRAIGHT_SHIP.
NEXT_SHIP:
  LD DE,$0004             ; Next entry
  ADD IX,DE               ;
  LD A,$00                ;
  DEC A                   ; Next ship
  JR NZ,PK_SHIP           ;
  JP HUNT                 ; None: hunt
PK_DAMAGED:
  LD A,($FDFE)            ; Put off the next peek (HUNT)
  LD ($FD35),A            ;
  LD A,B                  ; Straight ships (cruiser, destroyers, torpedo
  CP $04                  ; boat)...
  JP NC,STRAIGHT_SHIP     ;
  CP $02                  ;
  JP Z,STRAIGHT_SHIP      ;
  JP ODD_SHIP             ; ... and the others

; Step in a direction
;
; Moves DE one cell in the direction HL points at. If the column would leave
; the board, DE is unchanged; if only the row would, the column has moved and
; the row is off the board.
;
; I:DE Cell
; I:HL Direction (dx, dy)
; O:DE Next cell
; O:F Carry if it's on the board
STEP:
  PUSH HL                 ; Column
  LD A,(HL)               ;
  ADD A,D                 ;
  CP $14                  ;
  JR NC,ST_OFF            ;
  LD D,A                  ;
  INC HL                  ; Row
  LD A,(HL)               ;
  ADD A,E                 ;
  CP $14                  ;
  LD E,A
ST_OFF:
  POP HL
  RET

; Point at a direction
;
; Used by the routines at ROOM_FOR_SHIP, NEXT_TO_HITS, ODD_SHIP, STRAIGHT_SHIP
; and LINE_SHOT.
;
; I:A Direction 0-7 (up, up-right, right, ... clockwise)
; O:HL Its (dx, dy) in the table at $A874
DIRECTION:
  ADD A,A
  LD HL,DIRS
  ADD A,L
  LD L,A
  RET NC
  INC H
  RET

; The line through two hits
;
; Finds the next hit on the same ship after the one at HL, and the direction
; from it back to the first. Used for straight ships only.
;
; I:B Ship number
; I:DE First hit
; I:HL Its address
; O:B Direction from the second hit to the first
; O:C 1 if they are next to each other, 2 if there's a gap
; O:DE Second hit
; O:HL Pointer to the direction
SECOND_HIT:
  PUSH DE                 ; Find the next hit
  INC HL                  ;
  CALL FIND_HIT           ;
  POP HL                  ; HL = first hit, keep the second
  PUSH DE                 ;
  LD C,$01                ; C = 1: next to each other
  LD A,H                  ; D = sign of the column difference...
  SUB D                   ;
  LD D,A                  ;
  JR Z,SH_ROWS            ;
  LD D,$01
  JR NC,SH_COLS
  LD D,$FF
SH_COLS:
  CP D                    ; ... and a gap if it isn't 1
  JR Z,SH_ROWS            ;
  LD C,$02                ;
SH_ROWS:
  LD A,L                  ; The same for the rows
  SUB E                   ;
  LD E,A                  ;
  JR Z,SH_FIND            ;
  LD E,$01                ;
  JR NC,SECOND_HIT_0      ;
  LD E,$FF                ;
SECOND_HIT_0:
  CP E                    ;
  JR Z,SH_FIND            ;
  LD C,$02                ;
SH_FIND:
  LD HL,DIRS              ; Look up (D, E) in the table of directions
  LD B,$00                ;
SH_LOOP:
  LD A,(HL)
  INC HL
  CP D
  JR NZ,SECOND_HIT_1
  LD A,(HL)
  CP E
  JR Z,SH_FOUND
SECOND_HIT_1:
  INC HL
  INC B
  JR SH_LOOP
SH_FOUND:
  DEC HL
  POP DE
  RET

; Unused
;
; Nothing calls it.
UNUSED_3:
  DEC A
  BIT 7,A
  RET Z
  CP (IX+$03)
  RET NZ
  INC (IX+$02)
  RET

; Does this cell touch hits?
;
; For the carrier and submarine: with only one hit, any cell next to it will
; do; after that, a cell must touch at least two hit cells (of any ship).
;
; I:DE Cell
; I:IX Entry of the ship
; O:F NZ if it's good
NEXT_TO_HITS:
  LD ($A7D1),DE           ; Keep the cell in the operand at $A7D1
  PUSH DE                 ; C = hits still to find
  PUSH HL                 ;
  PUSH BC                 ;
  LD C,$02                ;
  LD A,(IX+$00)           ; One hit so far? Good
  DEC A                   ;
  JR Z,NH_GOOD            ;
  XOR A                   ; B = direction 0
  LD B,A                  ;
NH_LOOP:
  CALL DIRECTION          ; Step from the cell (self-modified operand)
  LD DE,$0000             ;
  CALL STEP               ;
  JR NC,NH_NEXT           ; Not off the board, not a miss...
  CALL CELL               ;
  INC A                   ;
  JR Z,NH_NEXT            ;
  DEC A                   ; ... and hit? Count it
  RLA                     ;
  JR C,NH_HIT             ;
NH_NEXT:
  INC B                   ; Next direction; Z when all 8 are done
  LD A,B                  ;
  CP $08                  ;
  JR Z,NH_RETURN          ;
  JR NH_LOOP              ;
NH_HIT:
  DEC C                   ; Two hits? Good
  JR NZ,NH_NEXT           ;
NH_GOOD:
  INC C                   ; NZ
NH_RETURN:
  POP BC
  POP HL
  POP DE
  RET

; The carrier's last cell
;
; With 5 hits on the carrier, the AI simply looks up where its last cell is:
; the board holds the unhit ship cells too.
LAST_CELL:
  CALL FIND_VALUE         ; Find the cell holding 1, the carrier's number
  CALL PLANNED            ; Planned already? Try the next hit (NEXT_ANCHOR),
  JR NZ,NEXT_ANCHOR       ; which finds nothing
  JP SET_TARGET           ; Shoot it

; Finish off the carrier or the submarine
;
; Takes the ship's hits one by one (in board order), and around each looks at
; the 8 directions, starting from a random one: the neighbour, if it's unshot,
; or the cell beyond if the neighbour is a hit, will do if it touches the hits
; (NEXT_TO_HITS).
;
; I:B Ship number
; I:IX Its entry
ODD_SHIP:
  LD HL,($A4D8)           ; HL = the board
  LD A,(IX+$00)           ; 5 hits (the carrier)? Go for the last cell
  CP $05                  ;
  JR Z,LAST_CELL          ;
  CALL FIND_HIT           ; The first hit
  LD (IX+$03),B           ; Remember the ship in the entry
  JR AROUND_HIT           ;
; This entry point is used by the routine at LAST_CELL.
NEXT_ANCHOR:
  LD HL,$0000             ; HL = after the last hit tried (self-modified
  INC HL                  ; operand)
  LD B,(IX+$03)           ; The next hit on the ship; none? Next ship
  CALL FIND_HIT           ;
  JP NC,NEXT_SHIP
AROUND_HIT:
  LD ($A810),HL           ; Remember where it is
  LD ($FDEE),DE           ; $FDEE = the hit
  CALL RANDOM             ; First direction: random; C = where we stop
  AND $07                 ;
  LD B,A                  ;
  LD C,A                  ;
  JR AH_DIRECTION
AH_NEXT:
  INC B                   ; Next direction
  LD A,B                  ;
  AND $07                 ;
  LD B,A                  ;
  CP C                    ; All 8 tried? Next hit
  JP Z,NEXT_ANCHOR        ;
AH_DIRECTION:
  LD DE,($FDEE)           ; Step from the hit; off the board? Next direction
  CALL DIRECTION          ;
  CALL STEP               ;
  JR NC,AH_NEXT           ;
  CALL PLANNED            ; Planned? Next
  JR NZ,AH_NEXT           ;
  CALL CELL               ; A miss? Next
  INC A                   ;
  JR Z,AH_NEXT            ;
  DEC A                   ; Hit? Look beyond
  RLA                     ;
  JR C,AH_BEYOND          ;
  CALL NEXT_TO_HITS       ; Unshot: good if it touches the hits
  JR Z,AH_NEXT            ;
AH_TARGET:
  JP SET_TARGET
AH_BEYOND:
  CALL STEP               ; One more step; off the board? Next
  JR NC,AH_NEXT           ;
  CALL PLANNED            ; Planned? Next
  JR NZ,AH_NEXT           ;
  CALL CELL               ; A miss? Next
  INC A                   ;
  JR Z,AH_NEXT            ;
  DEC A                   ; Hit? Next
  RLA                     ;
  JP C,AH_NEXT            ;
  CALL NEXT_TO_HITS       ; Unshot: good if it touches the hits
  JR Z,AH_NEXT            ;
  JR AH_TARGET            ;

; Directions
;
; (dx, dy) for up, up-right, right, down-right, down, down-left, left, up-left.
; Direction XOR 4 is the opposite.
DIRS:
  DEFB $00,$FF
  DEFB $01,$FF
  DEFB $01,$00
  DEFB $01,$01
  DEFB $00,$01
  DEFB $FF,$01
  DEFB $FF,$00
  DEFB $FF,$FF

; Finish off a straight ship
;
; With one hit: first the cell two away in some direction, with the one between
; not a miss; then a neighbour whose opposite neighbour isn't a miss. The
; torpedo boat (TORPEDO_BOAT) just takes a neighbour. With two or more hits:
; ALONG_LINE.
;
; I:B Ship number
; I:IX Its entry
STRAIGHT_SHIP:
  LD HL,($A4D8)           ; The first hit
  CALL FIND_HIT           ;
  LD ($FDEE),DE           ; $FDEE = the hit
  LD A,(IX+$00)           ; More than one hit? Extend the line
  DEC A                   ;
  JP NZ,ALONG_LINE        ;
  XOR A                   ; A' = cells two away found planned
  EX AF,AF'               ;
  CALL RANDOM             ; First direction: random
  AND $07                 ;
  LD B,A                  ;
  LD C,A                  ;
  JR SS_DIRECTION
SS_NEXT:
  LD DE,($FDEE)           ; Back to the hit
  INC B                   ; Next direction; all 8 tried?
  LD A,B                  ;
  AND $07                 ;
  LD B,A                  ;
  CP C                    ;
  JR Z,SS_NONE            ;
SS_DIRECTION:
  CALL DIRECTION
  LD A,($A73E)            ; The torpedo boat goes its own way
  CP $06                  ;
  JP Z,TORPEDO_BOAT       ;
  CALL STEP               ; Step; off the board? Next
  JR NC,SS_NEXT
  CALL CELL               ; A miss? Next
  INC A                   ;
  JR Z,SS_NEXT            ;
  CALL PLANNED            ; Planned? Next
  JR NZ,SS_NEXT           ;
  CALL STEP               ; One more step; off the board? Next
  JR NC,SS_NEXT           ;
  CALL CELL               ; Shot (hit or miss)? Next
  RLA                     ;
  JR C,SS_NEXT            ;
  CALL PLANNED            ; Not planned: that's the target
  JR Z,SET_TARGET         ;
  EX AF,AF'               ; Planned: count it, and next
  INC A                   ;
  EX AF,AF'               ;
  JR SS_NEXT              ;
; This entry point is used by the routines at LAST_CELL, ODD_SHIP, LINE_SHOT
; and HUNT.
SET_TARGET:
  LD ($FDCB),DE           ; The target is DE
  JP PK_DONE              ;
SS_NONE:
  EX AF,AF'               ; None found. If some were planned, and the enemy has
  JR Z,SS_NEIGHBOUR       ; more ships, work on the next ship
  LD A,($FDAD)            ;
  DEC A                   ;
  JP NZ,NEXT_SHIP         ;
SS_NEIGHBOUR:
  XOR A                   ; Now the neighbours, from a random direction
  EX AF,AF'               ;
  CALL RANDOM             ;
  AND $07                 ;
  LD B,A                  ;
  LD C,A                  ;
  JR SS_N_DIRECTION       ;
SS_N_NEXT:
  LD DE,($FDEE)           ; Next direction; all 8 tried? Next ship
  INC B                   ;
  LD A,B                  ;
  AND $07                 ;
  LD B,A                  ;
  CP C                    ;
  JR Z,SS_NEXT_SHIP       ;
SS_N_DIRECTION:
  CALL DIRECTION          ; Step; off the board? Next
  CALL STEP               ;
  JR NC,SS_N_NEXT         ;
  CALL CELL               ; Shot? Next
  RLA                     ;
  JR C,SS_N_NEXT          ;
  CALL PLANNED            ; Planned? Next
  JR NZ,SS_N_NEXT         ;
  LD ($A93C),DE           ; Keep it (in the operand at $A93C)
  LD A,B                  ; The opposite neighbour; off the board or a miss?
  XOR $04                 ; Next
  CALL DIRECTION          ;
  LD DE,($FDEE)           ;
  CALL STEP               ;
  JR NC,SS_N_NEXT         ;
  CALL CELL               ;
  INC A                   ;
  JR Z,SS_N_NEXT          ;
  CALL PLANNED            ; Not planned: the target is the neighbour
  JR Z,SS_N_TARGET        ;
  LD A,($FDAD)            ; Planned: only if it's the enemy's last ship
  DEC A                   ;
  JR NZ,SS_N_NEXT         ;
SS_N_TARGET:
  LD DE,$0000             ; The neighbour (self-modified operand)
  JP SET_TARGET           ;
SS_NEXT_SHIP:
  JP NEXT_SHIP
TORPEDO_BOAT:
  XOR A                   ; From a random direction
  EX AF,AF'               ;
  CALL RANDOM             ;
  AND $07                 ;
  LD B,A                  ;
  LD C,A                  ;
  JR TB_DIRECTION         ;
TB_NEXT:
  LD DE,($FDEE)           ; Next direction; all 8 tried? Next ship
  INC B                   ;
  LD A,B                  ;
  AND $07                 ;
  LD B,A                  ;
  CP C                    ;
  JR Z,SS_NEXT_SHIP       ;
TB_DIRECTION:
  CALL DIRECTION          ; Step; off the board? Next
  CALL STEP               ;
  JR NC,TB_NEXT           ;
  CALL CELL               ; Shot? Next
  RLA                     ;
  JR C,TB_NEXT            ;
  CALL PLANNED            ; Planned? Next
  JR NZ,TB_NEXT           ;
  PUSH DE                 ; The opposite direction
  LD A,B                  ;
  XOR $04                 ;
  CALL DIRECTION          ;
  LD A,($FDAD)            ; The enemy's last ship? Take it
  DEC A                   ;
  JR Z,TB_DONE            ;
  LD DE,($FDEE)           ; Otherwise only if the opposite neighbour isn't
  CALL STEP               ; planned (the step isn't checked)
  CALL PLANNED            ;
TB_DONE:
  POP DE
  JR NZ,TB_NEXT
  JP SET_TARGET
ALONG_LINE:
  LD (IX+$02),$32         ; Loop counter for the cruiser: 50
  CALL SECOND_HIT         ; The second hit, and the way from it to the first
  DEC C                   ; Next to each other? Look past the ends
  JR Z,AL_ENDS            ;
; A gap between them: fill it.
AL_GAP:
  LD ($A9D2),DE           ; Keep the cell (in the operand at $A9D2)
  CALL STEP               ; Step towards the first hit
  JR NC,AL_NEXT_SHIP      ;
  CALL CELL               ; Shot? Keep going
  RLA                     ;
  JR C,AL_GAP             ;
  CALL PLANNED            ; Not planned: the target
  JR Z,AL_TARGET          ;
  LD C,$00                ; Planned: count the cells planned
AL_GAP_2:
  INC C                   ; Step on
  CALL STEP               ;
  JR NC,AL_NEXT_SHIP      ;
  CALL CELL               ; Shot? Look past the ends
  RLA                     ;
  JR C,AL_GAP_DONE
  CALL PLANNED            ; Planned? Keep going
  JR NZ,AL_GAP_2          ;
AL_TARGET:
  JP SET_TARGET           ; The target
AL_NEXT_SHIP:
  JP NEXT_SHIP
AL_GAP_DONE:
  LD A,($A73E)            ; Only the cruiser looks further...
  CP $02                  ;
  JR NZ,AL_NEXT_SHIP      ;
  LD A,(IX+$00)           ; ... while its hits plus planned cells are under 5
  ADD A,C                 ;
  CP $05                  ;
  JR NC,AL_NEXT_SHIP      ;
  LD DE,$0000             ; From the cell before the gap (self-modified
                          ; operand)
; Past the second hit, away from the first.
AL_ENDS:
  LD A,B                  ; The opposite direction
  XOR $04                 ;
  CALL DIRECTION          ;
AL_END_1:
  CALL STEP               ; Step; off the board? The other end
  JR NC,AL_END_2          ;
  CALL CELL               ; A miss? The other end
  INC A                   ;
  JR Z,AL_END_2           ;
  DEC A                   ; Hit? Keep going
  RLA                     ;
  JR C,AL_END_1           ;
  LD ($AA26),DE           ; Keep the cell (in the operand at $AA26)
  CALL PLANNED            ; Not planned: the target. Planned: count it
  JP Z,SET_TARGET         ;
  INC C                   ;
; Past the first hit.
AL_END_2:
  LD DE,($FDEE)
  LD A,B
  CALL DIRECTION
AL_END_2_LOOP:
  CALL STEP               ; Step; off the board? Done
  JR NC,AL_MORE           ;
  CALL CELL               ; A miss? Done
  INC A                   ;
  JR Z,AL_MORE            ;
  DEC A                   ; Hit? Keep going
  RLA                     ;
  JR C,AL_END_2_LOOP      ;
  LD ($FDEE),DE           ; Remember it as $FDEE
  CALL PLANNED            ; Not planned: the target. Planned: count it
  JP Z,SET_TARGET         ;
  INC C                   ;
AL_MORE:
  LD A,($A73E)            ; Only the cruiser, with hits plus planned under 5,
  CP $02                  ; carries on...
  JR NZ,AL_NEXT_SHIP      ;
  LD A,(IX+$00)           ;
  ADD A,C                 ;
  CP $05                  ;
  JR NC,AL_NEXT_SHIP      ;
  LD DE,$0000             ; ... past the planned cell at this end
                          ; (self-modified operand)...
  DEC (IX+$02)            ; ... 50 times at most
  JR NZ,AL_ENDS           ;
  JR AL_NEXT_SHIP

; Hunt along a line
;
; From the cursor (the last shot placed, or the top left corner at the start of
; a turn), moved by -1..2 in each direction, go 1-4 cells at a time in the
; line's direction ($FDF4) to an unshot cell where a ship could be. Off the
; board: start a new line.
LINE_SHOT:
  LD DE,($A14A)           ; The cursor
  CALL RANDOM             ; Row -1..2
  AND $03                 ;
  DEC A                   ;
  ADD A,E                 ;
  LD E,A                  ;
  CALL RANDOM             ; Column -1..2
  AND $03                 ;
  DEC A                   ;
  ADD A,D                 ;
  LD D,A                  ;
  LD A,($FDF4)            ; The line's direction
  CALL DIRECTION          ;
  LD B,$04
LS_STEP:
  CALL STEP               ; Step; off the board? New line
  JR NC,LS_NEW_LINE       ;
  CALL RND_KEEP_HL        ; Stop here, half the time...
  RLA                     ;
  JR C,LS_CELL            ;
  DJNZ LS_STEP            ; ... or after 4 steps
LS_CELL:
  INC B
  CALL CELL               ; Shot? Step on
  RLA                     ;
  JR C,LS_STEP            ;
  CALL ROOM_FOR_SHIP      ; Room for a ship? That's the target
  JR NZ,LS_STEP           ;
  JP SET_TARGET           ;
LS_NEW_LINE:
  CALL NEW_AREA
  JP PK_DONE

; Hunt
;
; Hunting goes in blocks (BLOCK_SHOT) or in lines (LINE_SHOT). And every 29
; picks ($FDFE, in a one-player game) the AI peeks: it scans the board from a
; random place for a cell of a ship nobody has hit, targets it, and hunts in
; its block from then on.
HUNT:
  DEC (IY+$35)            ; Time to peek?
  JP NZ,BLOCK_SHOT        ;
; The peek.
  LD A,($FDFE)            ; Reset the count
  LD ($FD35),A            ;
  LD BC,$0190             ; Look at up to 400 cells
  CALL RANDOM             ; E = row: 0-18
  AND $03                 ;
  LD E,A                  ;
  CALL RANDOM             ;
  AND $0F                 ;
  ADD A,E                 ;
  LD E,A
  CALL RANDOM             ; D = column: 0-3
  AND $03                 ;
  LD D,A                  ; A random 0-15 is added, but never stored in D (a
  CALL RANDOM             ; bug)
  AND $0F                 ;
  ADD A,D                 ;
  CALL RANDOM             ; H = direction: +1 or -1
  AND $01                 ;
  JR NZ,HU_DIR            ;
  CPL                     ;
HU_DIR:
  LD H,A
; This entry point is used by the routine at HU_SCAN_NEXT.
HU_SCAN:
  LD A,D                  ; Next column...
  ADD A,H                 ;
  CP $14                  ;
  LD D,A                  ;
  JR C,HU_LOOK            ;
  LD A,H                  ; ... off the right edge?
  DEC A                   ;
  JR Z,HU_WRAP_RIGHT      ;
  LD D,$13                ; Off the left: the end of the row above
  DEC E                   ;
  LD A,E                  ;
  INC A                   ;
  JR NZ,HU_LOOK           ;
  LD E,$13                ;
  JR HU_LOOK              ;
HU_WRAP_RIGHT:
  LD D,A                  ; Off the right: the start of the row below
  INC E                   ;
  LD A,E                  ;
  CP $14                  ;
  JR C,HU_LOOK            ;
  LD E,$00                ;
HU_LOOK:
  CALL CELL               ; Open sea? Next
  JR Z,HU_SCAN_NEXT       ;
  RLA                     ; Shot? Next
  JR C,HU_SCAN_NEXT       ;
  CALL PLANNED            ; Planned? Next
  JR NZ,HU_SCAN_NEXT      ;
  PUSH DE                 ; An unhit ship! C = its block
  LD A,E                  ;
  CALL DIV5               ;
  LD A,B                  ;
  ADD A,A                 ;
  ADD A,A                 ;
  LD C,A                  ;
  LD A,D                  ;
  CALL DIV5               ;
  LD A,B                  ;
  ADD A,C                 ;
  LD C,A                  ;
  LD HL,$FD2B             ; Hunt in that block (SET_AREA with $FD2B set to 5 so
  LD A,(HL)               ; it takes block C)
  PUSH AF                 ;
  LD (HL),$05             ;
  CALL HU_SET_AREA        ;
  POP AF                  ;
  LD (HL),A               ;
  POP DE                  ; And target the ship
  JP SET_TARGET           ;
HU_SET_AREA:
  PUSH HL                 ; Call SET_AREA
  JP SET_AREA             ;

; Divide by 5
;
; Used by the routine at HUNT.
;
; I:A Number
; O:B Number / 5
DIV5:
  LD B,$00
DIV5_0:
  SUB $05
  RET C
  INC B
  JR DIV5_0

; Hunt (continued)
;
; Used by the routine at HUNT.
HU_SCAN_NEXT:
  DEC BC                  ; Next cell
  LD A,B                  ;
  OR C                    ;
  JR NZ,HU_SCAN           ;
; Hunt in a block: a short random walk from where the last shot in it was.
BLOCK_SHOT:
  LD HL,$FDEA             ; Shots for this block done? Find another block or
  LD A,(HL)               ; line
  OR A                    ;
  CALL Z,NEW_AREA         ;
  DEC (HL)
  LD A,($FDF3)            ; In a line?
  DEC A                   ;
  JP Z,LINE_SHOT          ;
  INC L                   ; E = first row of the block
  LD A,(HL)               ;
  AND $0C                 ;
  RRA                     ;
  RRA                     ;
  LD E,A                  ;
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,E                 ;
  LD E,A                  ;
  LD A,(HL)               ; D = first column
  AND $03                 ;
  LD D,A                  ;
  ADD A,A                 ;
  ADD A,A                 ;
  ADD A,D                 ;
  LD D,A                  ;
  LD (IY+$28),$78         ; 120 tries
BK_TRY:
  CALL RANDOM             ; Column in the block ($FDED) -1..2, wrapping round
  LD B,A                  ;
  AND $03                 ;
  DEC A                   ;
  LD HL,($FDEC)           ;
  ADD A,H                 ;
  CP $05
  JR C,BK_COLUMN
  SUB $05
  BIT 7,A
  JR Z,BK_COLUMN
  ADD A,$0A
BK_COLUMN:
  LD H,A                  ; Row in the block ($FDEC) -1..2, wrapping round
  LD A,B                  ;
  AND $0C                 ;
  RRA                     ;
  RRA                     ;
  DEC A                   ;
  ADD A,L                 ;
  CP $05                  ;
  JR C,BK_CELL            ;
  SUB $05
  BIT 7,A
  JR Z,BK_CELL
  ADD A,$0A
BK_CELL:
  LD L,A                  ; The cell
  LD ($FDEC),HL           ;
  ADD HL,DE               ;
  EX DE,HL                ; Good to hunt?
  CALL HUNTABLE           ;
  EX DE,HL                ;
  JR NZ,BK_NEXT           ; Then that's the target
  LD ($FDCB),HL           ;
; This entry point is used by the routines at STRAIGHT_SHIP and LINE_SHOT.
PK_DONE:
  XOR A                   ; Don't move this time
  LD ($FD03),A            ;
  RET                     ;
BK_NEXT:
  DEC (IY+$28)            ; Try again
  JR NZ,BK_TRY            ;
  XOR A                   ; Nothing in this block: find another next time...
  LD ($FDEA),A            ;
  INC (IY+$07)            ; ... and change the random numbers ($FD07 is their
  JR PK_DONE              ; top byte)

; Where to hunt next
;
; While there are 2 or more blocks without a shot, hunt in lines: start from a
; random open cell, and hunt in a random direction from there. The start cell
; is the target, and the AI makes sure it's open sea: its first shot always
; misses.
;
; Otherwise, hunt in a block: look for one other than the current block with no
; more than about the average shots; but then (SET_AREA) take the block with
; the fewest shots anyway.
NEW_AREA:
  PUSH HL                 ; Blocks without a shot
  LD A,($FD2B)            ;
  CP $02                  ;
  JR C,NA_BLOCK           ;
  LD A,$01                ; In a line; 12 shots
  LD ($FDF3),A            ;
  LD A,$0C                ;
  LD ($FDEA),A            ;
; The start of the line. The row's random byte comes right after the column's,
; and the two share 7 bits: whatever the random numbers, only 32 of the 256
; cells can come up. When they have all been shot, this loop never ends, and
; the game hangs.
NA_START:
  CALL RANDOM             ; Column 2-17
  AND $0F                 ;
  ADD A,$02               ;
  PUSH AF                 ; Row 2-17
  CALL RANDOM             ;
  AND $0F                 ;
  ADD A,$02               ;
  LD L,A                  ;
  POP AF                  ;
  LD H,A                  ;
  LD ($FDCB),HL           ; That's the target
  EX DE,HL                ; Not open sea? Try again
  CALL CELL               ;
  JR NZ,NA_START          ;
  CALL ROOM_FOR_SHIP      ; No room for a ship? Try again
  JR NZ,NA_START          ;
  CALL RANDOM             ; The line's direction
  AND $07                 ;
  LD ($FDF4),A            ;
  POP HL                  ;
  RET                     ;
NA_BLOCK:
  LD (IY+$28),$64         ; 100 tries
NA_TRY:
  CALL RANDOM             ; A random block, other than the current one
  AND $0F                 ;
  LD C,A                  ;
  LD A,($FDEB)            ;
  CP C                    ;
  JR Z,NA_TRY
  LD A,C                  ; No more than about the average shots? Take it
  ADD A,A                 ;
  LD HL,$F900             ;
  LD L,A                  ;
  LD A,($FDE8)            ;
  CP (HL)                 ;
  JR NC,SET_AREA
  DEC (IY+$28)            ; Try again
  JR NZ,NA_TRY            ;
  LD A,($FD29)            ; Out of tries: the block with the fewest shots
  LD C,A                  ;

; Hunt in a block
;
; Starts in the middle of the block, for 7-10 shots. The block is C only if 4
; or more blocks are without a shot (which in the game only happens after a
; peek); otherwise the one with the fewest shots.
;
; I:C Block
; I:(SP) HL to restore
SET_AREA:
  LD A,$02                ; Middle of the block
  LD ($FDED),A            ;
  LD ($FDEC),A            ;
  LD A,($FD2B)            ; Block C, or the emptiest
  CP $04                  ;
  LD A,C                  ;
  JR NC,SET_AREA_0        ;
  LD A,($FD29)            ;
SET_AREA_0:
  LD ($FDEB),A
  XOR A                   ; Not in a line
  LD ($FDF3),A            ;
  CALL RANDOM             ; 7-10 shots
  AND $03                 ;
  ADD A,$07               ;
  LD ($FDEA),A            ;
  POP HL
  RET

; Unused: target a random cell
;
; A random cell that hasn't been shot or planned. Nothing calls it: it looks
; like the first, plain version of the AI.
UNUSED_2:
  CALL RANDOM
  AND $1F
  CP $14
  JR NC,UNUSED_2
  LD E,A
UNUSED_2_0:
  CALL RANDOM
  AND $1F
  CP $14
  JR NC,UNUSED_2_0
  LD D,A
  CALL UNUSED_1
  JR C,UNUSED_2
  LD ($FDCB),DE
  XOR A
  LD ($FD03),A
  RET

